trigger:
  branches:
    include:
    - feature/*

pr:
  branches:
    include:
    - feature/*

pool:
  name: azsdk-pool-mms-win-2022-general
  vmImage: windows-2022

extends:
  template: templates/pipeline/build.yml
  parameters:
    BuildAlphaVersion: true
    UseTypeSpecNext: false
    IncludeTestStage: true
    PublishPackages: false
    PublishDependsOn: []
    PublishTarget: none
